name: Cpp CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      uses: lukka/get-cmake@latest

    - name: Configure with CMake
      run: cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release

    - name: Build with Ninja
      run: cmake --build build --config Release

    - name: Run tests
      run: ctest --test-dir build --output-on-failure
